name: Feature
description: Suggest a new feature.
labels: ["triage"]
type: Feature
assignees:
  - beauchama
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature. Please fill in the information below to help us understand your new feature.
        Please search to see if the requested feature has already been suggested ([quack.runtimes/issues](https://github.com/kappaduck/quack.runtimes/issues))
  - type: textarea
    id: feature-description
    attributes:
      label: >-
        Is your feature request related to a missing runtime feature.
      description: A clear and concise description of what the feature is.
      placeholder: I would like to have support for XYZ in the Quack runtimes...
    validations:
      required: false
